;subconverter外部配置（Terminal）
;参考：https://github.com/tindy2013/subconverter/blob/master/base/config/example_external_config.ini
[custom]
enable_rule_generator=true
overwrite_original_rules=true


;主策略组
custom_proxy_group=🚀 代理加速`select`[]🚩 香港节点`[]🍌 台湾节点`[]🦁 狮城节点`[]👺 日本节点`[]🗽 美国节点`[]🗺️ 其他节点`[]DIRECT
custom_proxy_group=🤖 人工智能`select`[]🚩 香港节点`[]🍌 台湾节点`[]🦁 狮城节点`[]👺 日本节点`[]🗽 美国节点`[]🗺️ 其他节点`[]DIRECT
custom_proxy_group=📺 国外媒体`select`[]🚩 香港节点`[]🍌 台湾节点`[]🦁 狮城节点`[]👺 日本节点`[]🗽 美国节点`[]🗺️ 其他节点`[]DIRECT
custom_proxy_group=🌏 国内站点`select`[]DIRECT`[]🚀 代理加速
custom_proxy_group=🐬 漏网之鱼`select`[]🚀 代理加速`[]DIRECT

;地区延迟自动测试策略组（每5s测试一次，容差10ms；Meta 内核支持手动选择）
custom_proxy_group=🚩 香港节点`url-test`(香港|HK|((?i)Hong Kong)|🇭🇰)`http://www.google.com/generate_204`5,,10
custom_proxy_group=🍌 台湾节点`url-test`(台湾|TW|((?i)Taiwan)|🇹🇼)`http://www.google.com/generate_204`5,,10
custom_proxy_group=🦁 狮城节点`url-test`(狮城|新加坡|SG|((?i)Singapore)|🇸🇬)`http://www.google.com/generate_204`5,,10
custom_proxy_group=👺 日本节点`url-test`(日本|JP|((?i)Japan)|🇯🇵)`http://www.google.com/generate_204`5,,10
custom_proxy_group=🗽 美国节点`url-test`(美国|US|((?i)United States)|🇺🇲)`http://www.google.com/generate_204`5,,10
custom_proxy_group=🗺️ 其他节点`select`^(?!.*?(香港|HK|((?i)Hong Kong)|🇭🇰|台湾|TW|((?i)Taiwan)|🇹🇼|狮城|新加坡|SG|((?i)Singapore)|🇸🇬|日本|JP|((?i)Japan)|🇯🇵|美国|US|((?i)United States)|🇺🇲)).*$


;规则集（更新间隔为120秒）
ruleset=DIRECT,clash-classic:rules/RikudouPatrickstar/lan-domain.yaml,120
ruleset=🤖 人工智能,clash-classic:rules/RikudouPatrickstar/ai.yaml,120
ruleset=🌏 国内站点,clash-classic:rules/RikudouPatrickstar/douyin-domain.yaml,120
ruleset=📺 国外媒体,clash-classic:rules/RikudouPatrickstar/global-media-domain.yaml,120
ruleset=🚀 代理加速,clash-classic:rules/RikudouPatrickstar/google-domain.yaml,120
ruleset=🌏 国内站点,surge:rules/RikudouPatrickstar/apple-direct.list,120
ruleset=🚀 代理加速,surge:rules/RikudouPatrickstar/apple-proxy.list,120
ruleset=🌏 国内站点,clash-domain:rules/RikudouPatrickstar/cn-domain.yaml,120
ruleset=🚀 代理加速,clash-classic:rules/RikudouPatrickstar/proxy-domain.yaml,120
ruleset=DIRECT,clash-classic:rules/RikudouPatrickstar/lan-ip.yaml,120
ruleset=📺 国外媒体,clash-classic:rules/RikudouPatrickstar/global-media-ip.yaml,120
ruleset=🚀 代理加速,clash-classic:rules/RikudouPatrickstar/google-ip.yaml,120
ruleset=🌏 国内站点,[]GEOIP,CN
ruleset=🐬 漏网之鱼,[]FINAL
