[RikudouPatrickstar]
name=RikudouPatrickstar
url=https://github.com/RikudouPatrickstar/Files
branch=master
match=rules/rule-sets/**

[RikudouPatrickstar_config]
name=RikudouPatrickstar
url=https://github.com/RikudouPatrickstar/Files
branch=master
match=rules/*.ini
dest=base/config/
keep_tree=false
